# Generated by Django 3.1.6 on 2021-02-22 22:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_auto_20210223_0343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suser',
            new_name='StudentUser',
        ),
    ]
