# Generated by Django 3.1.6 on 2021-04-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Recruiter',
            new_name='recruiter',
        ),
    ]
